"""
r01_layout.py -- Patrones de layout disponibles.
Gemini elige segun DESIGN.md, no el mas comun.
"""

LAYOUT_PATTERNS = (
    "=== LAYOUT PATTERNS -- ELIGE SEGUN DESIGN.MD, NO EL MAS COMUN ===\n\n"
    "HERO VARIANTS:\n"
    "  A) Full-viewport split: texto izquierda 50% + imagen derecha 50%.\n"
    "  B) Full-bleed con overlay: imagen de fondo + gradiente oscuro + texto centrado/izquierda.\n"
    "  C) Tipografia dominante: sin imagen. Headline clamp(4rem,10vw,9rem) ocupa 70% pantalla.\n"
    "  D) Asimetrico: texto en tercio izquierdo, imagen derecha en su propio contenedor.\n"
    "  E) Minimal: solo tipografia + 1 CTA, fondo solido del color primario o negro.\n"
    "  F) Magazine editorial: imagen derecha hasta el borde, texto izquierda en su columna.\n\n"
    "SECTION VARIANTS (alterna, no repitas el mismo entre secciones):\n"
    "  - Bento grid: CSS grid con grid-template-areas, celdas de tamanos variados,\n"
    "    cada celda es un contenedor independiente, NINGUNA se superpone a otra.\n"
    "  - Alternating split: imagen/texto lado a lado, alterna orden por seccion.\n"
    "  - Feature con numero gigante: numero 01/02 con opacity baja de fondo,\n"
    "    contenido real ENCIMA en flujo normal (position: relative, z-index limpio).\n"
    "  - Horizontal scroll carousel: overflow-x auto, scroll-snap, cada item en su carril.\n"
    "  - Full-bleed: background a 100vw, contenido centrado encima con overlay.\n"
    "  - Stat blocks: grid 3-4 columnas, numero grande + label, sin imagen.\n"
    "  - Quote full-section: blockquote centrado, fondo color solido.\n\n"
    "CARD VARIANTS:\n"
    "  - Image-top: imagen arriba (aspect-ratio 4/3), texto debajo -- SIN superposicion.\n"
    "  - Overlay: imagen de fondo + gradiente + texto -- legible porque el gradiente cubre.\n"
    "  - Horizontal: imagen izquierda 40% + texto derecha 60%, en sus columnas.\n"
    "  - Number card: numero grande arriba, titulo y descripcion debajo.\n"
    "  - Glassmorphism: solo si DESIGN.md lo indica explicitamente.\n\n"
    "NAVIGATION VARIANTS:\n"
    "  - Sticky top clasico (mayoria de casos).\n"
    "  - Minimal: solo logo + 1 CTA, sin links.\n"
    "  - Sidebar vertical (portfolios/dashboards).\n"
)
