"""
r01_layout.py -- Patrones de layout disponibles.
"""

LAYOUT_PATTERNS = (
    "=== LAYOUT PATTERNS -- ELIGE SEGUN DESIGN.MD, NO EL MAS COMUN ===\n\n"
    "REGLA CRITICA: USA EXACTAMENTE UN (1) HERO. Nunca dos secciones hero seguidas.\n"
    "El hero es la primera seccion. El resto son secciones distintas con layouts propios.\n\n"

    "HERO VARIANTS (elige UNO solo):\n"
    "  A) Full-viewport split: texto izquierda 50% + imagen derecha 50%.\n"
    "  B) Full-bleed con overlay: imagen de fondo + gradiente oscuro + texto centrado/izquierda.\n"
    "  C) Tipografia dominante: sin imagen. Headline clamp(4rem,10vw,9rem) ocupa 70% pantalla.\n"
    "  D) Asimetrico: texto en tercio izquierdo, imagen derecha en su propio contenedor.\n"
    "  E) Minimal: solo tipografia + 1 CTA, fondo solido del color primario o negro.\n"
    "  F) Magazine editorial: imagen derecha hasta el borde, texto izquierda en su columna.\n\n"

    "HERO TEXT CONTAINER (obligatorio en cualquier variante):\n"
    "  .hero-content { width: 100%; max-width: 650px; }  /* width:100% SIEMPRE */\n"
    "  Dentro de flex/grid: flex: 1; min-width: 0; para que el texto respire.\n"
    "  En mobile: padding-right: 0; width: 100%;\n\n"

    "BENTO GRID -- REGLAS TECNICAS OBLIGATORIAS:\n"
    "  PROBLEMA COMUN: cards colapsan a 0px porque las filas no tienen altura.\n"
    "  SOLUCION OBLIGATORIA:\n"
    "    .bento-grid {\n"
    "      display: grid;\n"
    "      grid-template-columns: repeat(6, 1fr);  /* o el numero de columnas elegido */\n"
    "      grid-auto-rows: 280px;  /* OBLIGATORIO: sin esto las filas colapsan */\n"
    "      gap: 16px;\n"
    "    }\n"
    "  Las imagenes dentro de cards bento:\n"
    "    .card-img { width: 100%; height: 100%; object-fit: cover; }\n"
    "    Esto funciona SOLO porque el padre ya tiene altura definida por grid-auto-rows.\n"
    "  REGLA DE COLUMNAS: los span de cada fila DEBEN sumar exactamente al total.\n"
    "    Con 6 columnas: cada fila debe tener cards que sumen exactamente 6.\n"
    "    Con 4 columnas: cada fila debe sumar 4. Nunca dejar columnas vacias.\n"
    "  RESPONSIVE BENTO: en @media 768px simplificar a grid de 1 o 2 columnas:\n"
    "    .bento-grid { grid-template-columns: 1fr 1fr; grid-auto-rows: 200px; }\n"
    "    .card { grid-column: span 1 !important; grid-row: span 1 !important; }\n\n"

    "SECTION VARIANTS (alterna, no repitas el mismo):\n"
    "  - Alternating split: imagen/texto lado a lado, alterna orden por seccion.\n"
    "  - Feature con numero gigante: numero 01/02 opacity baja de fondo.\n"
    "  - Full-bleed: background a 100vw, contenido centrado encima con overlay.\n"
    "  - Stat blocks: grid 3-4 columnas, numero grande + label.\n"
    "  - Quote full-section: blockquote centrado, fondo color solido.\n\n"

    "CARD VARIANTS:\n"
    "  - Image-top: imagen con aspect-ratio 4/3 (NO height:100% sin padre definido).\n"
    "    .card-img { width: 100%; aspect-ratio: 4/3; object-fit: cover; }\n"
    "  - Overlay: card con background-image + gradiente. Legible porque gradiente cubre.\n"
    "  - Horizontal: imagen izquierda 40% + texto derecha 60%.\n"
    "  - Number card: numero grande arriba, titulo y descripcion debajo.\n\n"

    "NAVIGATION VARIANTS:\n"
    "  - Sticky top clasico. Minimal: logo + 1 CTA.\n"
    "  - Sidebar vertical (portfolios/dashboards).\n"
)
