"""
r03_visual.py -- Principios de diseno visual: composicion, jerarquia, botones, iconos.
"""

VISUAL_PRINCIPLES = (
    "=== PRINCIPIOS DE DISENO VISUAL PREMIUM ===\n\n"

    "ANTI-GENERICO -- ESTAS COSAS ESTAN PROHIBIDAS:\n"
    "  x Botones rectangulares planos color solido sin efecto visual\n"
    "  x Secciones alternando fondo blanco / fondo gris\n"
    "  x Cards identicas en grid uniforme 3 columnas sin variacion\n"
    "  x Titulos h2 centrados + parrafo centrado + boton = PATRON PROHIBIDO\n"
    "  x Separadores <hr> o dividers planos entre secciones\n\n"

    "BOTONES -- CSS OBLIGATORIO:\n"
    "  Todo boton DEBE tener: min-width: 160px; width: auto; white-space: nowrap;\n"
    "  padding: 14px 32px; font-weight: 600; cursor: pointer; border-radius: 6px;\n"
    "  NUNCA dejar que un boton se comprima al tamano del texto. Siempre min-width.\n"
    "  El boton primario DEBE tener al menos UNO de estos tratamientos visuales:\n"
    "  OPCION A -- Gradiente animado:\n"
    "    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));\n"
    "    background-size: 200% 200%; animation: gradient-shift 3s ease infinite;\n"
    "    @keyframes gradient-shift { 0%,100%{background-position:0% 50%} 50%{background-position:100% 50%} }\n"
    "    color: #fff;\n"
    "  OPCION B -- Borde iluminado (ideal en fondos oscuros):\n"
    "    background: transparent; border: 2px solid var(--color-primary);\n"
    "    box-shadow: 0 0 20px rgba(var(--color-primary-rgb),0.4);\n"
    "    color: var(--color-primary); letter-spacing: 0.08em; text-transform: uppercase; font-size: 0.8rem;\n"
    "    transition: box-shadow 0.3s;\n"
    "    :hover { box-shadow: 0 0 40px rgba(var(--color-primary-rgb),0.7); background: rgba(var(--color-primary-rgb),0.08); }\n"
    "  OPCION C -- Solido con elevation hover:\n"
    "    background: var(--color-primary); color: #fff;\n"
    "    transition: transform 0.2s, box-shadow 0.2s;\n"
    "    :hover { transform: translateY(-3px); box-shadow: 0 12px 30px rgba(0,0,0,0.3); }\n"
    "    :active { transform: translateY(-1px); }\n\n"

    "NAV UNDERLINE -- BUG CRITICO (el mas comun):\n"
    "  El selector ::after para subrayar links de nav DEBE evitar botones:\n"
    "    CORRECTO: .nav-links-list a::after { ... }\n"
    "    CORRECTO: .nav-links ul a::after { ... }\n"
    "    CORRECTO: .nav-links a:not(.btn):not(.btn-primary)::after { ... }\n"
    "    MAL:      .nav-links a::after { ... }  <-- afecta botones CTA en el nav\n"
    "  El error se ve como una linea extra bajo el boton Contactar / CTA del nav.\n\n"

        "RIQUEZA VISUAL -- CADA SECCION DEBE TENER AL MENOS UNO:\n"
    "  - Gradiente sutil en el fondo (linear o radial usando variables del DESIGN.md)\n"
    "  - Elemento decorativo: ::before/::after con forma, o div con blur(80px)\n"
    "  - Numero gigante con opacity: 0.06 de fondo como decoracion\n"
    "  - Overlay de textura: background-image: repeating-linear-gradient(...)\n"
    "  Los fondos NO son simplemente colores solidos. Tienen profundidad.\n\n"

    "CARDS PREMIUM:\n"
    "  box-shadow: 0 4px 6px rgba(0,0,0,.07), 0 20px 40px rgba(0,0,0,.12);\n"
    "  :hover { transform: translateY(-6px); box-shadow: 0 24px 50px rgba(0,0,0,.18); }\n"
    "  transition: transform 0.3s cubic-bezier(0.34,1.56,0.64,1), box-shadow 0.3s;\n"
    "  Cards con imagen: zoom en hover:\n"
    "    .card-img { overflow: hidden; }\n"
    "    .card-img img { transition: transform 0.5s; }\n"
    "    .card:hover .card-img img { transform: scale(1.08); }\n\n"

    "COMPOSICION:\n"
    "  Alterna alineacion por seccion: izquierda / derecha / centrado. Nunca todo centrado.\n"
    "  Layout 2 columnas: 62% principal + 38% secundaria (proporcion aurea).\n"
    "  Cada columna de un grid de 2 debe tener peso visual similar.\n"
    "  Columna vacia = bug visual. Llenar con stat, features, quote o mockup.\n\n"

    "JERARQUIA TIPOGRAFICA:\n"
    "  Escala obligatoria (ver valores exactos en r07_technical TIPOGRAFIA):\n"
    "    H1/Hero:    clamp(3.5rem, 7vw, 7rem)   -- impacto maximo\n"
    "    H2/Section: clamp(2rem, 4vw, 3.5rem)   -- visible sin scroll\n"
    "    H3/Card:    clamp(1.25rem, 2vw, 1.75rem)\n"
    "    Body:       clamp(0.95rem, 1.5vw, 1.1rem) con line-height: 1.7\n"
    "  Letter-spacing: -0.04em en H1, -0.02em en H2, 0 en body.\n"
    "  Contraste de tamano: H1 debe ser al menos 2.5x el tamano del body.\n"
    "  Nunca texto centrado en parrafos largos (>8 palabras). Solo en titulares cortos.\n"
    "  max-width: 65ch en todos los parrafos para legibilidad optima.\n\n"

    "OVERLINE / EYEBROW (obligatorio):\n"
    "  Antes de cada titulo de seccion: <span class=\"overline\">LABEL EN MAYUS</span>\n"
    "  CSS: text-transform:uppercase; letter-spacing:0.15em; font-size:0.75rem;\n"
    "       color:var(--color-primary); font-weight:600; display:block; margin-bottom:0.5rem;\n\n"

    "ICONOS -- REGLAS CRITICAS (errores frecuentes):\n"
    "  Usar SVG inline o Unicode. NUNCA font-icon externo sin CDN garantizado.\n"
    "  Todo SVG DEBE tener: width='24' height='24' viewBox='0 0 24 24' fill='none'\n"
    "    stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'\n"
    "  El CONTENEDOR del icono NUNCA tiene overflow:hidden -- eso corta el trazo.\n"
    "  Icono en flex: el contenedor del icono DEBE tener flex-shrink:0 para no comprimirse.\n"
    "  Tamano del contenedor: width:48px; height:48px; display:flex; align-items:center; justify-content:center;\n"
    "  Si el icono va dentro de un circulo/badge, el circulo DEBE ser al menos 2x el tamano del SVG.\n"
    "    Ejemplo: SVG 24px -> contenedor min 48px. SVG 32px -> contenedor min 64px.\n"
    "  Siempre con texto label excepto iconos universales (home, cerrar, buscar).\n"
    "  Color: color:var(--color-primary) o stroke:var(--color-primary) en el SVG directamente.\n"

    "NIELSEN -- DISENO ESTETICO Y MINIMALISTA (KISS):\n"
    "  No incluir elementos decorativos que no guien al usuario ni comuniquen nada.\n"
    "  Prohibido: animaciones CSS blink/flash, popups al cargar, banners de cookie intrusivos.\n"
    "  Cada elemento tiene un proposito. Si no lo tiene, se elimina.\n"
    "  Coherencia: mismos estilos para elementos del mismo tipo en todo el sitio.\n"
    "  Formularios: labels visibles siempre (no solo placeholder). Botones con verbo descriptivo.\n"
)
