"""
r03_visual.py -- Principios de diseno visual: composicion, jerarquia, botones, iconos.
"""

VISUAL_PRINCIPLES = (
    "=== PRINCIPIOS DE DISENO VISUAL ===\n\n"
    "COMPOSICION:\n"
    "  Regla de tercios: alterna alineacion por seccion (izquierda / derecha / centrado).\n"
    "  Nunca todo centrado -- se ve estatico.\n"
    "  CTA principal en los puntos de interseccion de la cuadricula 3x3.\n"
    "  Layout 2 columnas: jerarquia 62% principal + 38% secundaria (proporcion aurea).\n\n"
    "EQUILIBRIO:\n"
    "  Cada columna de un grid de 2 debe tener peso visual similar.\n"
    "  Imagen grande izquierda = texto largo derecha (no texto de 2 lineas).\n"
    "  PROHIBIDO columna vacia: llenar con stat, lista de features, testimonial o mockup.\n\n"
    "JERARQUIA TIPOGRAFICA:\n"
    "  Nivel 1 hero: mas grande, mas contraste. Min 2.5rem mobile, 4rem desktop.\n"
    "  Nivel 2 subtitulos: medios. Nivel 3 cuerpo: 16-18px. Nivel 4 labels: pequeno/muted.\n"
    "  Minimo 2x diferencia de tamano entre niveles adyacentes.\n"
    "  Texto centrado SOLO en titulares cortos (max 2-3 lineas). NUNCA en parrafos.\n\n"
    "BOTONES:\n"
    "  Altura minima 44px. Padding 12px vertical / 24px horizontal. cursor: pointer.\n"
    "  :hover con cambio perceptible. :active con scale(0.97).\n"
    "  Maximo 1 CTA primario por seccion. Si hay secundario: menor prominencia visual.\n"
    "  Labels: verbo + objeto ('Ver galeria', 'Reservar ahora'). Nunca 'Click aqui', 'Submit'.\n\n"
    "ICONOS:\n"
    "  Siempre con texto label excepto home/buscar/cerrar.\n"
    "  Tamano consistente: 16px, 20px o 24px segun contexto.\n"
    "  Color = color del texto que los acompana.\n"
    "  Iconos solos: obligatorio aria-label o title descriptivo.\n"
)
