"""
r06_interactive.py -- Reglas de implementacion de componentes interactivos.
Solo se incluye si el brief menciona carrusel, slider, galeria, tabs o acordeon.
"""

INTERACTIVE_COMPONENTS = (
    "=== COMPONENTES INTERACTIVOS ===\n\n"
    "PRINCIPIO: todo componente interactivo tiene modo automatico + modo manual.\n\n"

    "CARRUSEL / SLIDER -- IMPLEMENTACION EXACTA (copia este patron):\n"
    "CRITICO: el contenedor externo DEBE tener overflow:hidden o todos los slides seran visibles.\n\n"
    "HTML:\n"
    "  <div class=\"carousel-wrapper\">\n"
    "    <div class=\"carousel-track\">\n"
    "      <div class=\"carousel-slide\"><!-- contenido slide 1 --></div>\n"
    "      <div class=\"carousel-slide\"><!-- contenido slide 2 --></div>\n"
    "      <div class=\"carousel-slide\"><!-- contenido slide 3 --></div>\n"
    "    </div>\n"
    "    <button class=\"carousel-btn carousel-prev\" aria-label=\"Anterior\">&#8249;</button>\n"
    "    <button class=\"carousel-btn carousel-next\" aria-label=\"Siguiente\">&#8250;</button>\n"
    "    <div class=\"carousel-dots\"></div>\n"
    "  </div>\n\n"
    "CSS OBLIGATORIO (sin esto los slides aparecen todos a la vez):\n"
    "  .carousel-wrapper {\n"
    "    position: relative;\n"
    "    overflow: hidden;  /* OBLIGATORIO: sin esto todos los slides son visibles */\n"
    "    width: 100%;\n"
    "  }\n"
    "  .carousel-track {\n"
    "    display: flex;\n"
    "    transition: transform 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94);\n"
    "    will-change: transform;\n"
    "  }\n"
    "  .carousel-slide {\n"
    "    min-width: 100%;  /* OBLIGATORIO: cada slide ocupa el 100% del wrapper */\n"
    "    flex-shrink: 0;\n"
    "  }\n"
    "  .carousel-btn {\n"
    "    position: absolute; top: 50%; transform: translateY(-50%);\n"
    "    background: rgba(255,255,255,0.85); border: none; cursor: pointer;\n"
    "    width: 40px; height: 40px; border-radius: 50%;\n"
    "    font-size: 1.5rem; line-height: 1; z-index: 10;\n"
    "  }\n"
    "  .carousel-prev { left: 16px; }\n"
    "  .carousel-next { right: 16px; }\n\n"
    "JS OBLIGATORIO:\n"
    "  let idx = 0;\n"
    "  const track = document.querySelector('.carousel-track');\n"
    "  const slides = document.querySelectorAll('.carousel-slide');\n"
    "  const total = slides.length;\n"
    "  function goTo(n) {\n"
    "    idx = (n + total) % total;\n"
    "    track.style.transform = `translateX(-${idx * 100}%)`;\n"
    "  }\n"
    "  document.querySelector('.carousel-prev').onclick = () => goTo(idx - 1);\n"
    "  document.querySelector('.carousel-next').onclick = () => goTo(idx + 1);\n"
    "  let timer = setInterval(() => goTo(idx + 1), 6500);\n"
    "  document.querySelector('.carousel-wrapper').onmouseenter = () => clearInterval(timer);\n"
    "  document.querySelector('.carousel-wrapper').onmouseleave = () => {\n"
    "    timer = setInterval(() => goTo(idx + 1), 6500);\n"
    "  };\n\n"
    "Multi-item (N visibles): .carousel-slide { min-width: calc(100% / N); }\n"
    "NUNCA translateX en pixeles -- siempre en porcentajes.\n"
    "Touch: touchstart/touchend, diff >50px = cambiar slide.\n\n"

    "TABS / ACORDEON: solo por click. Clase .active con estilo diferenciado.\n"
    "  Acordeon: transicion con max-height o opacity+transform.\n\n"
    "HOVER: 100% CSS. Cards: translateY(-4px) + shadow. Botones: scale(1.02).\n\n"
    "REVEAL (IntersectionObserver): automatico al entrar al viewport, no requiere click.\n"
)
