"""
r06_interactive.py -- Reglas de implementacion de componentes interactivos.
Solo se incluye si el brief menciona carrusel, slider, galeria, tabs o acordeon.
"""

INTERACTIVE_COMPONENTS = (
    "=== COMPONENTES INTERACTIVOS ===\n\n"
    "PRINCIPIO: todo componente interactivo tiene modo automatico + modo manual.\n\n"

    "CARRUSEL -- REGLAS CRITICAS DE IMAGENES (bugs mas comunes):\n"
    "  BUG 1 -- loading=lazy PROHIBIDO en slides:\n"
    "    Las imagenes en carousel-slide NO deben tener loading=lazy.\n"
    "    Razon: el browser no carga imagenes clippeadas por overflow:hidden + translateX\n"
    "    porque no las considera cerca del viewport. Cuando el carrusel llega al slide,\n"
    "    la imagen intenta cargar desde cero y aparece en blanco.\n"
    "    SOLUCION: NO poner atributo loading en imagenes de slides (o poner loading=eager).\n"
    "  BUG 2 -- clase .reveal PROHIBIDA en slides:\n"
    "    No aplicar .reveal ni IntersectionObserver a elementos dentro de carousel-slide.\n"
    "    Razon: los slides fuera de la vista tienen opacity:0 y el observer no los detecta\n"
    "    porque estan clippeados (no intersectan el viewport). Quedan invisibles.\n"
    "    SOLUCION: el carrusel no usa .reveal. Las imagenes estan visibles desde el start.\n\n"

    "CARRUSEL / SLIDER -- IMPLEMENTACION EXACTA (copia este patron):\n"
    "CRITICO: el contenedor externo DEBE tener overflow:hidden o todos los slides seran visibles.\n\n"
    "HTML:\n"
    "  <div class=\"carousel-wrapper\">\n"
    "    <div class=\"carousel-track\">\n"
    "      <div class=\"carousel-slide\"><!-- contenido slide 1 --></div>\n"
    "      <div class=\"carousel-slide\"><!-- contenido slide 2 --></div>\n"
    "      <div class=\"carousel-slide\"><!-- contenido slide 3 --></div>\n"
    "    </div>\n"
    "    <button class=\"carousel-btn carousel-prev\" aria-label=\"Anterior\">&#8249;</button>\n"
    "    <button class=\"carousel-btn carousel-next\" aria-label=\"Siguiente\">&#8250;</button>\n"
    "    <div class=\"carousel-dots\"></div>\n"
    "  </div>\n\n"
    "CSS OBLIGATORIO (sin esto los slides aparecen todos a la vez):\n"
    "  .carousel-wrapper { position:relative; overflow:hidden; width:100%; }\n"
    "  .carousel-track { display:flex; transition:transform 0.7s cubic-bezier(0.25,0.46,0.45,0.94); will-change:transform; }\n"
    "  .carousel-slide { min-width:100%; flex-shrink:0; }\n"
    "  .carousel-btn { position:absolute; top:50%; transform:translateY(-50%);\n"
    "    background:rgba(255,255,255,0.85); border:none; cursor:pointer;\n"
    "    width:40px; height:40px; border-radius:50%; font-size:1.5rem; line-height:1; z-index:10; }\n"
    "  .carousel-prev { left:16px; }\n"
    "  .carousel-next { right:16px; }\n\n"
    "JS OBLIGATORIO:\n"
    "  var carouselIdx = 0;\n"
    "  var carouselWrapper = document.querySelector('.carousel-wrapper');\n"
    "  var carouselTrack = document.querySelector('.carousel-track');\n"
    "  var carouselSlides = document.querySelectorAll('.carousel-slide');\n"
    "  var carouselTotal = carouselSlides.length;\n"
    "  function carouselGoTo(n) {\n"
    "    carouselIdx = (n + carouselTotal) % carouselTotal;\n"
    "    carouselTrack.style.transform = 'translateX(-' + (carouselIdx * 100) + '%)';\n"
    "  }\n"
    "  document.querySelector('.carousel-prev').onclick = function() { carouselGoTo(carouselIdx - 1); };\n"
    "  document.querySelector('.carousel-next').onclick = function() { carouselGoTo(carouselIdx + 1); };\n"
    "  var carouselTimer = setInterval(function() { carouselGoTo(carouselIdx + 1); }, 6500);\n"
    "  carouselWrapper.onmouseenter = function() { clearInterval(carouselTimer); };\n"
    "  carouselWrapper.onmouseleave = function() { carouselTimer = setInterval(function() { carouselGoTo(carouselIdx + 1); }, 6500); };\n\n"
    "Multi-item (N visibles): .carousel-slide { min-width: calc(100% / N); }\n"
    "NUNCA translateX en pixeles -- siempre en porcentajes.\n"
    "Touch: touchstart/touchend, diff >50px = cambiar slide.\n"
    "IMAGENES EN SLIDES: NO usar loading=lazy. NO usar clase .reveal. Deben cargarse de inmediato.\n\n"

    "TABS / ACORDEON: solo por click. Clase .active con estilo diferenciado.\n"
    "  Acordeon: transicion con max-height o opacity+transform.\n"
    "  IMAGENES EN TABS Y ACORDEON: NO usar loading=lazy si hay imagenes en paneles ocultos.\n"
    "    Con display:none, el browser no carga imagenes lazy. Al abrir el panel queda en blanco.\n"
    "  NUNCA aplicar clase .reveal a contenido dentro de tabs o acordeones.\n\n"
    "HOVER: 100% CSS. Cards: translateY(-4px) + shadow. Botones: scale(1.02).\n\n"
    "REVEAL (IntersectionObserver): automatico al entrar al viewport, no requiere click.\n"
    "  EXCLUSIONES del reveal: slides de carrusel, paneles de tabs, items de acordeon.\n"
    "  Aplicar .reveal solo a elementos directamente en el flujo del documento.\n\n"

    "GALERIA CON FILTROS Y BUSQUEDA -- IMPLEMENTACION OBLIGATORIA:\n"
    "Cuando el sitio tiene botones de categoria + campo de busqueda, SIEMPRE incluir este JS.\n"
    "Sin este codigo los filtros son puramente decorativos y no hacen nada.\n\n"
    "REQUISITOS DEL HTML:\n"
    "  1. Cada card tiene data-category con su categoria exacta:\n"
    "       <div class=\"photo-card\" data-category=\"Retratos\">...\n"
    "  2. El boton 'Todo' (o 'All') muestra todas las cards:\n"
    "       <button class=\"category-btn active\">Todo</button>\n"
    "  3. Los botones de categoria tienen textContent igual al valor en data-category:\n"
    "       <button class=\"category-btn\">Retratos</button>  <!-- debe coincidir exacto -->\n"
    "  4. El input de busqueda tiene clase .search-input:\n"
    "       <input type=\"search\" class=\"search-input\" placeholder=\"Buscar...\">\n\n"
    "JS OBLIGATORIO (en DOMContentLoaded):\n"
    "  var filterBtns = document.querySelectorAll('.category-btn');\n"
    "  var galleryItems = document.querySelectorAll('.gallery-grid .photo-card, .gallery-grid .gallery-item');\n"
    "  var searchInput = document.querySelector('.search-input');\n"
    "  var activeCategory = 'Todo';\n\n"
    "  function applyFilters() {\n"
    "    var searchTerm = searchInput ? searchInput.value.trim().toLowerCase() : '';\n"
    "    galleryItems.forEach(function(item) {\n"
    "      var cat = (item.dataset.category || '').trim();\n"
    "      var titleEl = item.querySelector('.card-title, h3, h2');\n"
    "      var title = titleEl ? titleEl.textContent.toLowerCase() : '';\n"
    "      var matchCat = (activeCategory === 'Todo' || activeCategory === 'All' || cat === activeCategory);\n"
    "      var matchSearch = (searchTerm === '' || title.includes(searchTerm));\n"
    "      item.style.display = (matchCat && matchSearch) ? '' : 'none';\n"
    "    });\n"
    "  }\n\n"
    "  filterBtns.forEach(function(btn) {\n"
    "    btn.addEventListener('click', function() {\n"
    "      filterBtns.forEach(function(b) { b.classList.remove('active'); });\n"
    "      btn.classList.add('active');\n"
    "      activeCategory = btn.textContent.trim();\n"
    "      applyFilters();\n"
    "    });\n"
    "  });\n\n"
    "  if (searchInput) {\n"
    "    searchInput.addEventListener('input', applyFilters);\n"
    "  }\n\n"
    "NOTA: Si el search input usa otra clase, ajustar el selector. El patron es identico.\n"
    "NOTA: 'Todo' en espanol, 'All' en ingles -- el boton reset debe mostrar todo.\n"
)
