"""
r07_technical.py -- Especificaciones tecnicas de CSS/HTML. Valores concretos.
Fuente de verdad para tamanos, espaciados, variables, responsive y animaciones.
"""

TECHNICAL_QUALITY = (
    "=== TECHNICAL QUALITY ===\n\n"
    "ESPACIADO (escala de 8px):\n"
    "  Secciones: padding 80px vertical desktop, 48px mobile.\n"
    "  Max-width 1200px centrado, padding 0 24px lateral.\n"
    "  Escala: 8 / 16 / 24 / 32 / 48 / 64 / 80px. No inventar valores fuera de escala.\n\n"
    "RESPONSIVE:\n"
    "  @media (max-width: 768px) en todos los componentes.\n"
    "  Mobile: columna unica, padding 24px lateral, botones full-width.\n"
    "  Hero mobile: min-height 60vh, texto legible, CTA visible sin scroll.\n\n"
    "TIPOGRAFIA (valores CSS):\n"
    "  Display: clamp(2.2rem, 5vw, 5rem). Headline: clamp(1.6rem, 3vw, 2.8rem).\n"
    "  Body: 16-18px, line-height 1.65, max-width 65ch.\n"
    "  Google Fonts: solo las fuentes definidas en DESIGN.md.\n\n"
    "IMAGENES:\n"
    "  object-fit: cover + dimensiones definidas en todos los contenedores.\n"
    "  img: crossorigin=anonymous. loading=lazy en todo excepto el hero.\n"
    "  Hero: background-image CSS, background-size: cover, background-position: center.\n"
    "  Nunca src vacio. Nunca placeholder.com.\n\n"
    "CSS VARIABLES:\n"
    "  Cada token YAML del DESIGN.md -> CSS custom property en :root.\n"
    "  Todos los colores del DESIGN.md deben aparecer usados en el CSS.\n\n"
    "CONTRASTE WCAG AA:\n"
    "  Texto sobre fondo: 4.5:1 minimo. Texto grande (>18px bold): 3:1 minimo.\n"
    "  Texto sobre imagen: overlay rgba oscuro obligatorio.\n\n"
    "ANIMACIONES:\n"
    "  .reveal { opacity: 0; transform: translateY(28px); transition: opacity 0.6s, transform 0.6s; }\n"
    "  .reveal.visible { opacity: 1; transform: none; }\n"
    "  IntersectionObserver activa .visible al entrar al viewport.\n"
    "  Aplicar a: titulares, cards, features. Stagger con nth-child delay.\n"
    "  Navbar: clase .scrolled cuando scrollY > 50px. Mobile toggle. scroll-behavior: smooth.\n\n"
    "IDIOMA:\n"
    "  Todo el texto del sitio en el mismo idioma que el brief.\n"
)
