"""
r07_technical.py -- Especificaciones tecnicas de CSS/HTML. Valores concretos.
"""

TECHNICAL_QUALITY = (
    "=== TECHNICAL QUALITY ===\n\n"

    "HERO -- LAYOUT CRITICO:\n"
    "  El hero ocupa min-height: 90vh desktop. NUNCA menos.\n"
    "  ALINEACION: text-align LEFT por defecto en el hero. NUNCA centrar el texto del hero.\n"
    "    Excepcion unica: variante C/E (solo tipografia, sin imagen) puede centrar.\n"
    "  TAMANO DEL HEADLINE DEL HERO (obligatorio):\n"
    "    font-size: clamp(3.5rem, 7vw, 7rem);  /* grande e impactante -- nunca pequeno */\n"
    "    font-weight: 800; letter-spacing: -0.04em; line-height: 1.05;\n"
    "    NUNCA font-size en px. NUNCA menor de 3.5rem.\n"
    "  COLUMNA DE TEXTO del hero:\n"
    "    flex: 1; min-width: min(520px, 100%); padding: 80px 64px;\n"
    "    display:flex; flex-direction:column; justify-content:center; gap:28px;\n"
    "    text-align: left; align-items: flex-start; /* SIEMPRE izquierda */\n"
    "  El texto NO se encapsula en un div pequeno fijo. La columna de texto respira.\n"
    "  BOTON CTA DEL HERO: padding: 18px 40px; font-size: 1rem; min-width: 200px;\n"
    "    Grande, prominente. Nunca tiny. Color solido o gradiente contrastante.\n"
    "  COLUMNA DE IMAGEN del hero: flex:1; overflow:hidden; height:100%;\n"
    "    object-fit:cover; width:100%; height:100%;\n\n"

    "REGLA DE ALINEACION -- CRITICA:\n"
    "  x PROHIBIDO: centrar parrafos, subtitulos o bloques de texto en secciones.\n"
    "  OK centrar: titulares h2 de 1-4 palabras (no el parrafo que los sigue).\n"
    "  OK centrar: stat blocks, quote sections, CTA sections aisladas.\n"
    "  NUNCA centrar texto en el hero. NUNCA centrar texto de cards.\n"
    "  La regla: si hay mas de 8 palabras seguidas, va alineado a la izquierda.\n\n"

    "EQUILIBRIO IMAGEN-TEXTO:\n"
    "  En secciones de 2 columnas: ninguna columna supera 60% del ancho.\n"
    "  Regla: 50/50 para impacto visual. 60/40 para enfasis en contenido.\n"
    "  Imagenes con aspect-ratio definido en su contenedor:\n"
    "    Hero imagen: aspect-ratio: 4/3 o 16/9\n"
    "    Card imagen: aspect-ratio: 4/3 (obligatorio)\n"
    "    Seccion split: la imagen tiene max-height: 500px en desktop\n\n"

    "RESPONSIVE -- CRITICO:\n"
    "  Cada contenedor de texto dentro de un flex/grid DEBE tener:\n"
    "    flex: 1; min-width: 0; (en flex) -- sin esto el texto no respira\n"
    "    width: 100%; (en grid)\n"
    "  Titulares NUNCA en px fijo. SIEMPRE clamp() o vw.\n"
    "  word-break: break-word en todos los textos.\n"
    "  @media (max-width: 768px):\n"
    "    grid-template-columns: 1fr; flex-direction: column;\n"
    "    padding lateral: 24px; botones: width: 100%;\n"
    "  Hero mobile: flex-direction:column; min-height:60vh; texto primero, imagen debajo.\n\n"

    "TIPOGRAFIA (valores CSS):\n"
    "  Hero headline: clamp(3.5rem, 7vw, 7rem). font-weight: 800. letter-spacing: -0.04em.\n"
    "  Section headline: clamp(2rem, 4vw, 3.5rem). font-weight: 700. letter-spacing: -0.02em.\n"
    "  Body: 16-18px, line-height: 1.65, max-width: 65ch en parrafos.\n"
    "  Google Fonts: solo las fuentes definidas en DESIGN.md.\n\n"

    "IMAGENES:\n"
    "  object-fit: cover + aspect-ratio definido en TODOS los contenedores.\n"
    "  img: crossorigin=anonymous. loading=lazy en todo excepto hero.\n"
    "  Hero: background-image CSS, background-size:cover, background-position:center.\n"
    "  Nunca src vacio. Nunca placeholder.com.\n\n"

    "CSS VARIABLES:\n"
    "  Cada token YAML del DESIGN.md -> CSS custom property en :root.\n"
    "  Todos los colores del DESIGN.md deben aparecer usados en el CSS.\n\n"

    "CONTRASTE WCAG AA:\n"
    "  Texto sobre fondo: 4.5:1 minimo. Texto sobre imagen: overlay rgba oscuro obligatorio.\n\n"

    "FORMULARIOS -- REGLAS CRITICAS:\n"
    "  1. NUNCA usar input[type=number] -- usar type=text inputmode=numeric pattern=[0-9]*.\n"
    "     Esto elimina las flechitas de incremento.\n"
    "     Si se usa number igual, CSS para ocultar spinners:\n"
    "       input[type=number]::-webkit-inner-spin-button,\n"
    "       input[type=number]::-webkit-outer-spin-button { -webkit-appearance: none; margin: 0; }\n"
    "       input[type=number] { -moz-appearance: textfield; }\n"
    "  2. FECHAS -- pre-poblar con hoy:\n"
    "       document.querySelectorAll(\'input[type=date]\').forEach(inp => {\n"
    "         if (!inp.value) inp.value = new Date().toISOString().split(\'T\')[0];\n"
    "       });\n"
    "  3. HORAS -- pre-poblar con la hora actual:\n"
    "       document.querySelectorAll(\'input[type=time]\').forEach(inp => {\n"
    "         if (!inp.value) {\n"
    "           const now = new Date();\n"
    "           inp.value = now.getHours().toString().padStart(2,\'0\') + \':\' + now.getMinutes().toString().padStart(2,\'0\');\n"
    "         }\n"
    "       });\n"
    "     Ejecutar en DOMContentLoaded.\n"
    "  4. Cada <input> tiene su <label> visible (no solo placeholder).\n"
    "  5. Estados de error: border: 2px solid #dc2626; + texto rojo debajo del campo.\n\n"

    "ANIMACIONES -- OBLIGATORIAS:\n\n"
    "  1. REVEAL SCROLL (en titulares, cards, features):\n"
    "    .reveal { opacity:0; transform:translateY(32px);\n"
    "      transition: opacity 0.7s cubic-bezier(0.16,1,0.3,1), transform 0.7s cubic-bezier(0.16,1,0.3,1); }\n"
    "    .reveal.visible { opacity:1; transform:none; }\n"
    "    .reveal:nth-child(2){transition-delay:0.1s} .reveal:nth-child(3){transition-delay:0.2s}\n"
    "    JS: new IntersectionObserver((e)=>e.forEach(x=>x.isIntersecting&&x.target.classList.add(\'visible\')),{threshold:0.1})\n\n"
    "  2. CONTADOR NUMERICO en stats:\n"
    "    function countUp(el){const t=+el.dataset.target,suf=el.dataset.suffix||\'\'\n"
    "    let n=0;const s=t/60;const i=setInterval(()=>{n=Math.min(n+s,t);\n"
    "    el.textContent=Math.floor(n)+suf;if(n>=t)clearInterval(i)},16)}\n\n"
    "  3. NAVBAR SCROLL:\n"
    "    window.addEventListener(\'scroll\',()=>nav.classList.toggle(\'scrolled\',scrollY>50))\n"
    "    nav.scrolled { backdrop-filter:blur(20px); background:rgba(var(--nav-bg-rgb),0.85); }\n\n"
    "  4. PARALLAX HERO: window.addEventListener(\'scroll\',()=>hero.style.backgroundPositionY=scrollY*0.4+\'px\')\n\n"
    "  5. HOVER MAGNETICO en CTA principal (max 1-2 por pagina):\n"
    "    btn.addEventListener(\'mousemove\',(e)=>{const r=btn.getBoundingClientRect();\n"
    "    btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*0.3}px,${(e.clientY-r.top-r.height/2)*0.3}px)`})\n"
    "    btn.addEventListener(\'mouseleave\',()=>btn.style.transform=\'\')\n\n"
    "  scroll-behavior:smooth en html. Mobile nav toggle funcional.\n\n"

    "ACCESIBILIDAD:\n"
    "  a:focus-visible, button:focus-visible, input:focus-visible {\n"
    "    outline: 2px solid var(--color-primary); outline-offset: 3px; border-radius: 4px; }\n"
    "  Imagenes: alt descriptivo siempre. Botones de solo icono: aria-label obligatorio.\n"
)
