"""
r07_technical.py -- Especificaciones tecnicas de CSS/HTML. Valores concretos.
"""

TECHNICAL_QUALITY = (
    "=== TECHNICAL QUALITY ===\n\n"

    "OVERFLOW PREVENTION -- ESTAS REGLAS VAN PRIMERO EN EL CSS, SIN EXCEPCION:\n"
    "  *, *::before, *::after { box-sizing: border-box; }\n"
    "  html { overflow-x: hidden; }\n"
    "  body { overflow-x: hidden; max-width: 100%; }\n"
    "  img, video, iframe, canvas { max-width: 100%; height: auto; display: block; }\n"
    "  svg { max-width: 100%; overflow: visible; } /* NO display:block global -- SVG icons inside buttons/links must stay inline */\n"
    "  button svg, a svg, label svg, span svg { display: inline-block; vertical-align: middle; flex-shrink: 0; } /* icon SVGs */\n"
    "  BOTONES CON ICONOS: usar display:inline-flex; align-items:center; gap:8px; (NO inline-block)\n"
    "    Con inline-flex, el icono y el texto quedan en la misma linea automaticamente.\n"
    "    Con inline-block + SVG block, el icono ocupa toda la fila y el texto cae abajo -- ROTO.\n"
    "  FLEX CHILDREN: todo hijo directo de un flex container DEBE tener min-width: 0;\n"
    "    sin esto el texto dentro desborda el contenedor en pantallas pequenas.\n"
    "    Ejemplo: .hero { display:flex; } .hero > * { min-width: 0; }\n"
    "  GRID CHILDREN: toda celda de grid DEBE tener min-width: 0; por la misma razon.\n"
    "  TEXTO: todos los contenedores de parrafos y titulares DEBEN tener:\n"
    "    overflow-wrap: break-word; word-break: break-word;\n"
    "  NUNCA usar width fijo en px en elementos dentro de flex/grid.\n"
    "  NUNCA usar margin-left/right negativo que saque elementos fuera del viewport.\n"
    "  SECCIONES: cada seccion tiene width: 100%; no hay seccion con ancho mayor al viewport.\n"
    "  CONTENEDOR CANONICO (usar en todas las secciones):\n"
    "    .container { width: 100%; max-width: 1200px; margin: 0 auto;\n"
    "      padding-left: clamp(20px, 5vw, 80px); padding-right: clamp(20px, 5vw, 80px); }\n\n"

    "HERO -- LAYOUT CRITICO:\n"
    "  El hero ocupa min-height: 90vh desktop. NUNCA menos.\n"
    "  ALINEACION: text-align LEFT por defecto en el hero. NUNCA centrar el texto del hero.\n"
    "    Excepcion unica: variante C/E (solo tipografia, sin imagen) puede centrar.\n"
    "  TAMANO DEL HEADLINE DEL HERO (obligatorio):\n"
    "    font-size: clamp(3.5rem, 7vw, 7rem);  /* grande e impactante -- nunca pequeno */\n"
    "    font-weight: 800; letter-spacing: -0.04em; line-height: 1.05;\n"
    "    NUNCA font-size en px. NUNCA menor de 3.5rem.\n"
    "  COLUMNA DE TEXTO del hero:\n"
    "    flex: 1; min-width: min(520px, 100%); padding: 80px 64px;\n"
    "    display:flex; flex-direction:column; justify-content:center; gap:28px;\n"
    "    text-align: left; align-items: flex-start; /* SIEMPRE izquierda */\n"
    "  El texto NO se encapsula en un div pequeno fijo. La columna de texto respira.\n"
    "  BOTON CTA DEL HERO: padding: 18px 40px; font-size: 1rem; min-width: 200px;\n"
    "    Grande, prominente. Nunca tiny. Color solido o gradiente contrastante.\n"
    "  COLUMNA DE IMAGEN del hero: flex:1; overflow:hidden; height:100%;\n"
    "    object-fit:cover; width:100%; height:100%;\n\n"

    "REGLA DE ALINEACION -- CRITICA:\n"
    "  x PROHIBIDO: centrar parrafos, subtitulos o bloques de texto en secciones.\n"
    "  OK centrar: titulares h2 de 1-4 palabras (no el parrafo que los sigue).\n"
    "  OK centrar: stat blocks, quote sections, CTA sections aisladas.\n"
    "  NUNCA centrar texto en el hero. NUNCA centrar texto de cards.\n"
    "  La regla: si hay mas de 8 palabras seguidas, va alineado a la izquierda.\n\n"

    "EQUILIBRIO IMAGEN-TEXTO -- REGLAS CRITICAS (espacios vacios frecuentes):\n"
    "  En secciones de 2 columnas: ninguna columna supera 60% del ancho.\n"
    "  Regla: 50/50 para impacto visual. 60/40 para enfasis en contenido.\n"
    "  ANTI-ESPACIO-VACIO: la columna de imagen SIEMPRE llena su espacio:\n"
    "    .split-img { width:100%; height:100%; min-height:400px;\n"
    "      object-fit:cover; display:block; align-self:stretch; }\n"
    "  El CONTENEDOR de imagen en split-sections:\n"
    "    align-self: stretch;  /* se estira al alto de la columna de texto */\n"
    "    min-height: 400px;    /* piso minimo para no colapsar */\n"
    "    overflow: hidden;     /* contiene la imagen */\n"
    "  NUNCA dejar un div de imagen con height:auto en un flex container -> colapsa a 0.\n"
    "  Imagenes con aspect-ratio definido en su contenedor:\n"
    "    Hero imagen: aspect-ratio: 4/3 o 16/9\n"
    "    Card imagen: aspect-ratio: 4/3 (obligatorio)\n"
    "    Seccion split: la imagen tiene min-height:400px y align-self:stretch en desktop\n\n"

    "RESPONSIVE -- CRITICO:\n"
    "  VIEWPORT META TAG (OBLIGATORIO en todo HTML generado -- sin esto el sitio NO es responsive):\n"
    "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
    "    Colocar en el <head> SIEMPRE. Sin este tag, movil renderiza la pagina como desktop\n"
    "    y todo se ve minusculo e inutilizable.\n"
    "  CONTENEDOR DE TEXTO en flex/grid:\n"
    "    flex: 1; min-width: 0;  /* obligatorio en flex -- sin esto desborda */\n"
    "    overflow-wrap: break-word; word-break: break-word;\n"
    "  PADDING DE SECCIONES (fluido, no fijo):\n"
    "    Horizontal: padding-left: clamp(20px, 5vw, 80px); padding-right: clamp(20px, 5vw, 80px);\n"
    "    Vertical:   padding-top: clamp(60px, 8vw, 120px); padding-bottom: clamp(60px, 8vw, 120px);\n"
    "    NUNCA padding fijo como padding: 80px -- usar clamp() siempre.\n"
    "  Titulares NUNCA en px fijo. SIEMPRE clamp() (ver seccion TIPOGRAFIA arriba).\n"
    "  @media (max-width: 768px):\n"
    "    grid-template-columns: 1fr !important; flex-direction: column !important;\n"
    "    padding lateral: clamp(16px, 4vw, 24px);\n"
    "    botones: width: 100%; max-width: 400px;\n"
    "    gap reducido: gap: 1.5rem;\n"
    "  @media (max-width: 480px):\n"
    "    padding lateral: 16px;\n"
    "    font-size de subheadings: reducir min del clamp si es necesario.\n"
    "  Hero mobile: flex-direction:column; min-height:60vh; texto primero, imagen debajo.\n"
    "  Bento/galeria mobile: grid-template-columns: 1fr; grid-auto-rows: 220px;\n\n"

    "TIPOGRAFIA (valores CSS -- TODOS en clamp(), NUNCA px fijo en titulares):\n"
    "  Hero headline:    font-size: clamp(3.5rem, 7vw, 7rem);   font-weight: 800; letter-spacing: -0.04em; line-height: 1.05;\n"
    "  Section headline: font-size: clamp(2rem, 4vw, 3.5rem);   font-weight: 700; letter-spacing: -0.02em; line-height: 1.15;\n"
    "  Subheadline:      font-size: clamp(1.1rem, 2.2vw, 1.4rem); font-weight: 500; line-height: 1.4;\n"
    "  Body text:        font-size: clamp(0.95rem, 1.5vw, 1.1rem); line-height: 1.7; max-width: 65ch;\n"
    "  Caption/label:    font-size: clamp(0.8rem, 1.2vw, 0.875rem); line-height: 1.5;\n"
    "  REGLA: ningun texto usa px fijo. Todo headline usa clamp(). El body usa la escala de arriba.\n"
    "  Google Fonts: solo las fuentes definidas en DESIGN.md.\n\n"

    "IMAGENES:\n"
    "  object-fit: cover + aspect-ratio definido en TODOS los contenedores.\n"
    "  loading=lazy SOLO en imagenes que estan en el flujo normal del documento.\n"
    "  NUNCA loading=lazy en: slides de carrusel, paneles de tabs, items de acordeon.\n"
    "    Razon: estan clippeados (overflow:hidden) o hidden (display:none), el browser\n"
    "    no los carga y al mostrarlos quedan en blanco.\n"
    "  Hero: loading='eager' (carga prioritaria, no lazy).\n"
    "  NUNCA crossorigin=anonymous -- el iframe de preview tiene origen null y CORS falla.\n"
    "  Hero: background-image CSS, background-size:cover, background-position:center.\n"
    "  Contenedor de imagen card obligatorio:\n"
    "    .card-img { width: 100%; aspect-ratio: 4/3; overflow: hidden; }\n"
    "    .card-img img { width: 100%; height: 100%; object-fit: cover; display: block; }\n"
    "  Nunca src vacio. Nunca placeholder.com.\n\n"

    "CSS VARIABLES:\n"
    "  Cada token YAML del DESIGN.md -> CSS custom property en :root.\n"
    "  Todos los colores del DESIGN.md deben aparecer usados en el CSS.\n\n"

    "CONTRASTE WCAG AA:\n"
    "  Texto sobre fondo: 4.5:1 minimo. Texto sobre imagen: overlay rgba oscuro obligatorio.\n\n"

    "FORMULARIOS -- REGLAS CRITICAS:\n"
    "  1. NUNCA usar input[type=number] -- usar type=text inputmode=numeric pattern=[0-9]*.\n"
    "     Esto elimina las flechitas de incremento.\n"
    "     Si se usa number igual, CSS para ocultar spinners:\n"
    "       input[type=number]::-webkit-inner-spin-button,\n"
    "       input[type=number]::-webkit-outer-spin-button { -webkit-appearance: none; margin: 0; }\n"
    "       input[type=number] { -moz-appearance: textfield; }\n"
    "  2. FECHAS -- pre-poblar con hoy:\n"
    "       document.querySelectorAll('input[type=date]').forEach(inp => {\n"
    "         if (!inp.value) inp.value = new Date().toISOString().split('T')[0];\n"
    "       });\n"
    "  3. HORAS -- pre-poblar con la hora actual:\n"
    "       document.querySelectorAll('input[type=time]').forEach(inp => {\n"
    "         if (!inp.value) {\n"
    "           const now = new Date();\n"
    "           inp.value = now.getHours().toString().padStart(2,'0') + ':' + now.getMinutes().toString().padStart(2,'0');\n"
    "         }\n"
    "       });\n"
    "     Ejecutar en DOMContentLoaded.\n"
    "  4. Cada <input> tiene su <label> visible (no solo placeholder).\n"
    "  5. Estados de error: border: 2px solid #dc2626; + texto rojo debajo del campo.\n\n"

    "SINGLE-PAGE HTML -- NAVEGACION SEGURA (bug critico: links que rompen el preview):\n"
    "  Este HTML es un ARCHIVO UNICO. No existen otras paginas en el servidor.\n"
    "  Si un link navega fuera del contexto actual, rompe el preview del usuario.\n\n"
    "  REGLA 1 -- VIEWPORT META (sin esto el sitio no es responsive en movil):\n"
    "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
    "    OBLIGATORIO en el <head>. SIEMPRE. Sin excepcion.\n\n"
    "  REGLA 2 -- LINKS A SECCIONES REALES:\n"
    "    Usar href='#id-de-la-seccion' -- correcto, hace scroll a la seccion.\n"
    "    <a href='#features'>Features</a>  <- correcto\n\n"
    "  REGLA 3 -- LINKS A PAGINAS QUE NO EXISTEN (About, Blog, Portfolio, etc.):\n"
    "    PROHIBIDO: href='/about'  href='about.html'  href='/'  href=''  href='../'\n"
    "    Estas URLs navegan fuera del HTML y rompen el preview.\n"
    "    CORRECTO: href='#' onclick='return false'\n"
    "    O simplemente omitir el href si el link no tiene destino real.\n\n"
    "  REGLA 4 -- FORMULARIOS: e.preventDefault() SIEMPRE:\n"
    "    document.getElementById('mi-form').addEventListener('submit', function(e) {\n"
    "      e.preventDefault();\n"
    "      // validar + mostrar toast\n"
    "    });\n"
    "    Sin e.preventDefault(), al hacer submit el browser navega a una URL vacia\n"
    "    y rompe el preview completamente.\n\n"
    "  REGLA 5 -- BOTONES type=submit fuera de forms:\n"
    "    Agregar type='button' para que no disparen submit del form padre.\n"
    "    <button type='button' onclick='abrirModal()'>Ver mas</button>\n\n"
    "  RESUMEN: en un single-page HTML, NINGUN click debe navegar a una URL diferente.\n"
    "  Todos los links van a anclas (#id) o tienen onclick='return false'.\n"
    "  Todos los forms tienen e.preventDefault().\n\n"

    "ANIMACIONES -- OBLIGATORIAS:\n\n"
    "  1. REVEAL SCROLL (en titulares, cards, features):\n"
    "    .reveal { opacity:0; transform:translateY(32px);\n"
    "      transition: opacity 0.7s cubic-bezier(0.16,1,0.3,1), transform 0.7s cubic-bezier(0.16,1,0.3,1); }\n"
    "    .reveal.visible { opacity:1; transform:none; }\n"
    "    .reveal:nth-child(2){transition-delay:0.1s} .reveal:nth-child(3){transition-delay:0.2s}\n"
    "    JS: new IntersectionObserver((e)=>e.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:0.1})\n\n"
    "  2. CONTADOR NUMERICO en stats:\n"
    "    function countUp(el){const t=+el.dataset.target,suf=el.dataset.suffix||''\n"
    "    let n=0;const s=t/60;const i=setInterval(()=>{n=Math.min(n+s,t);\n"
    "    el.textContent=Math.floor(n)+suf;if(n>=t)clearInterval(i)},16)}\n\n"
    "  3. NAVBAR SCROLL:\n"
    "    window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>50))\n"
    "    nav.scrolled { backdrop-filter:blur(20px); background:rgba(var(--nav-bg-rgb),0.85); }\n\n"
    "  4. PARALLAX HERO: window.addEventListener('scroll',()=>hero.style.backgroundPositionY=scrollY*0.4+'px')\n\n"
    "  5. HOVER MAGNETICO en CTA principal (max 1-2 por pagina):\n"
    "    btn.addEventListener('mousemove',(e)=>{const r=btn.getBoundingClientRect();\n"
    "    btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*0.3}px,${(e.clientY-r.top-r.height/2)*0.3}px)`})\n"
    "    btn.addEventListener('mouseleave',()=>btn.style.transform='')\n\n"
    "  scroll-behavior:smooth en html. Mobile nav toggle funcional.\n\n"

    "ACCESIBILIDAD:\n"
    "  a:focus-visible, button:focus-visible, input:focus-visible {\n"
    "    outline: 2px solid var(--color-primary); outline-offset: 3px; border-radius: 4px; }\n"
    "  Imagenes: alt descriptivo siempre. Botones de solo icono: aria-label obligatorio.\n"
)
